### ISSUE TITLE
Pgsql 16 Segmentation fault

### ISSUE THREAD

**Issue by dainiusrid** [dverite/permuteseq#5]
LOG:  server process (PID 84359) was terminated by signal 11: Segmentation fault
Here:
params = DirectFunctionCall1(pg_sequence_parameters, seq_oid);

With pgsql15 builds and runs OK.

**Comment by dverite** [comment]
Indeed, this call can no longer work since Postgres 16. This is fixed by commit 9470bb36301af956e3772f757792a85a3c99355e
Thanks for the report!
